plugins:
  editorconfig:
    enabled: true
    exclude_patterns:
      - "examples/assets/*"
      - "src/assets/*"
      - "templates/*"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml"
